name: Upload to Google Drive

on:
  workflow_dispatch:  # 手动触发

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --no-cache-dir gdown pydrive

      - name: Save credentials to creds.json
        env:
          DRIVE_CREDENTIALS_JSON: ${{ secrets.DRIVE_CREDENTIALS_JSON }}
        run: echo "$DRIVE_CREDENTIALS_JSON" > creds.json

      - name: Find latest CSV
        id: find_csv
        run: |
          LATEST_CSV=$(ls -t data/股票池合并_核准_*.csv | head -n 1)
          echo "LATEST_CSV=$LATEST_CSV" >> $GITHUB_ENV

      - name: Upload to Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
        run: |
          python upload_to_gdrive.py
