name: Upload to Google Drive

on:
  # 手动运行
  workflow_dispatch:
  # 定时：北京时间 17:30（= UTC 09:30），周一至周五
  schedule:
    - cron: '30 9 * * 1-5'

# 防重入（可选）
concurrency:
  group: upload-to-drive
  cancel-in-progress: false

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      # 预检查：只找“今天(中国时区)的带日期CSV”，没有就跳过整个上传流程
      - name: Precheck – find today's dated CSV (China time)
        id: precheck
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          # 取北京时间今天的日期标签
          DATE_TAG=$(TZ=Asia/Shanghai date +%Y%m%d)
          echo "DATE_TAG=$DATE_TAG" >> "$GITHUB_ENV"

          # 查找 data/*_YYYYMMDD.csv
          files=(data/*_"${DATE_TAG}".csv)
          if [ ${#files[@]} -eq 0 ]; then
            echo "has_file=false" >> "$GITHUB_OUTPUT"
            echo "ℹ️ 今天($DATE_TAG)未发现带日期CSV，流程将跳过上传。"
            exit 0
          fi

          # 若有多份，取修改时间最新的一份
          UPLOAD_CSV=$(ls -t "${files[@]}" | head -n 1)
          echo "UPLOAD_CSV=$UPLOAD_CSV" >> "$GITHUB_ENV"
          echo "LATEST_CSV=$UPLOAD_CSV" >> "$GITHUB_ENV"
          echo "has_file=true" >> "$GITHUB_OUTPUT"
          echo "✅ 找到当日文件：$UPLOAD_CSV"

      - name: Set up Python
        if: steps.precheck.outputs.has_file == 'true'
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        if: steps.precheck.outputs.has_file == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      - name: Upload to Google Drive
        if: steps.precheck.outputs.has_file == 'true'
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          # LATEST_CSV / DATE_TAG 已在 Precheck 步写入 $GITHUB_ENV
        run: |
          python upload_to_gdrive.py

      # 当天没有文件时的收尾信息（成功结束）
      - name: Done / skipped
        if: steps.precheck.outputs.has_file != 'true'
        run: echo "今天未生成CSV，已跳过上传。"
