name: Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      # 寻找最新一份 CSV（你的目录/前缀保持不变）
      - name: Find latest CSV
        run: |
          set -e
          LATEST_CSV=$(ls -t "data/股票池合并_核准_*.csv" 2>/dev/null | head -n 1 || true)
          if [ -z "$LATEST_CSV" ]; then
            echo "没有匹配到 data/股票池合并_核准_*.csv"
            exit 1
          fi
          echo "LATEST_CSV=$LATEST_CSV" >> $GITHUB_ENV
          echo "✅ 选中的文件：$LATEST_CSV"

      # 关键：写入北京时间(UTC+8)的 YYYYMMDD 到环境变量 DATE_TAG
      - name: Set CN date (YYYYMMDD)
        run: |
          DATE_TAG=$(TZ=Asia/Shanghai date +%Y%m%d)
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          echo "📅 将使用日期：$DATE_TAG"

      - name: Upload to Google Drive
        env:
          # 四个机密来自 Secrets
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          # 这两个来自上面步骤写入的 GITHUB_ENV（写不写都行，写了更直观）
          LATEST_CSV: ${{ env.LATEST_CSV }}
          DATE_TAG: ${{ env.DATE_TAG }}
        run: |
          python upload_to_gdrive.py
