name: Upload to Google Drive

on:
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
      # 拉取代码
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir google-api-python-client google-auth google-auth-oauthlib google-auth-httplib2

      # 只使用“最新交易日”的带日期文件（data/*_YYYYMMDD.csv），否则报错
      - name: Find latest dated CSV (YYYYMMDD)
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob

          # 收集所有带日期后缀的 CSV
          files=(data/*_[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9].csv)

          if [ ${#files[@]} -eq 0 ]; then
            echo "❌ 没有找到 data/*_YYYYMMDD.csv（请先生成或同步带日期的 CSV）"
            exit 1
          fi

          # 按修改时间排序，取最新一份
          LATEST_CSV=$(ls -t "${files[@]}" | head -n 1)

          echo "✅ 选中的文件：$LATEST_CSV"
          echo "UPLOAD_CSV=$LATEST_CSV" >> $GITHUB_ENV
          echo "LATEST_CSV=$LATEST_CSV" >> $GITHUB_ENV

          # 从文件名中提取 YYYYMMDD 作为 DATE_TAG
          DATE_TAG=$(echo "$LATEST_CSV" | sed -E 's/.*_([0-9]{8})\.csv$/\1/')
          if [[ ! "$DATE_TAG" =~ ^[0-9]{8}$ ]]; then
            echo "❌ 无法从文件名解析日期：$LATEST_CSV"
            exit 1
          fi
          echo "DATE_TAG=$DATE_TAG" >> $GITHUB_ENV
          echo "📅 DATE_TAG: $DATE_TAG"

      - name: Upload to Google Drive
        env:
          GDRIVE_FOLDER_ID: ${{ secrets.GDRIVE_FOLDER_ID }}
          GDRIVE_CLIENT_ID: ${{ secrets.GDRIVE_CLIENT_ID }}
          GDRIVE_CLIENT_SECRET: ${{ secrets.GDRIVE_CLIENT_SECRET }}
          GDRIVE_REFRESH_TOKEN: ${{ secrets.GDRIVE_REFRESH_TOKEN }}
          # 这里的 LATEST_CSV / DATE_TAG 已在上一步写入 GITHUB_ENV，会自动注入到本 step 的环境变量
        run: |
          python upload_to_gdrive.py
